version: '3.8'

services:
  # Development version with hot reload
  multi-agent-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - RELOAD=true
    volumes:
      - ../src:/app/src
      - ../scripts:/app/scripts
      - ../logs:/app/logs
    restart: unless-stopped

  # Redis for development
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped