version: 2

sources:
  - name: raw
    description: Raw marketing data from multiple sources
    tables:
      - name: marketing_data
        description: Raw media spend and performance data
        columns:
          - name: date
            description: Date of media spend
            tests:
              - not_null
              - unique
          - name: tv_spend
            description: TV advertising spend in USD
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
                  max_value: 1000000
          - name: digital_spend
            description: Digital advertising spend in USD
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
                  max_value: 500000
          - name: conversions
            description: Total conversions
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
          - name: revenue
            description: Total revenue in USD
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0

models:
  - name: stg_media_spend
    description: Cleaned and standardized media spend data
    columns:
      - name: spend_date
        description: Date of media spend
        tests:
          - not_null
          - unique
      - name: total_media_spend_usd
        description: Total media spend across all channels
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 2000000
      - name: cost_per_conversion
        description: Cost per conversion metric
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1000
      - name: spend_to_revenue_ratio
        description: Spend to revenue ratio
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 2

  - name: stg_channel_performance
    description: Channel-level performance metrics
    columns:
      - name: spend_date
        description: Date of media spend
        tests:
          - not_null
      - name: channel
        description: Media channel name
        tests:
          - not_null
          - accepted_values:
              values: ['tv', 'digital', 'radio', 'print', 'social']
      - name: channel_spend_usd
        description: Channel spend in USD
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: channel_spend_share
        description: Channel spend as share of total spend
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1